name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Make application.properties
        run: |
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.PROPERTIES }}" > ./application.properties

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker login
        run: |
          echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u _json_key --password-stdin https://index.docker.io/v1/
      
      - name: Docker build & push to Docker Hub
        run: |
          docker build -t your-docker-username/your-repo-name:latest .
          docker push your-docker-username/your-repo-name:latest
